### ISSUE TITLE
Tabular numerics don't work in fixed-weight variants obtained from Google fonts

### ISSUE THREAD

**Issue by zlksnk** [sharanda/manrope#50]
Neither of the following properties enable tabular nums of Manrope when its fixed-weight variants are used from Google fonts:

```css
.tnum {
  font-feature-settings: "tnum";
  font-variant-numeric: tabular-nums;
}
```

---

Same issue is reported by others:
- https://github.com/sharanda/manrope/issues/2#issuecomment-620556375
