### ISSUE TITLE
Provide an easy way to use Manrope with woff2 format and variable font with latin unicode-range

### ISSUE THREAD

**Issue by Vadorequest** [sharanda/manrope#71]
When using the link generated by Google Font at https://fonts.googleapis.com/css2?family=Manrope&display=optional, it gives:

```css
/* cyrillic */
@font-face {
  font-family: 'Manrope';
  font-style: normal;
  font-weight: 400;
  font-display: optional;
  src: url(https://fonts.gstatic.com/s/manrope/v4/xn7_YHE41ni1AdIRqAuZuw1Bx9mbZk79FN_G-b_Tfc7AGraJwA.woff) format('woff');
  unicode-range: U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116;
}
/* greek */
@font-face {
  font-family: 'Manrope';
  font-style: normal;
  font-weight: 400;
  font-display: optional;
  src: url(https://fonts.gstatic.com/s/manrope/v4/xn7_YHE41ni1AdIRqAuZuw1Bx9mbZk79FN_B-b_Tfc7AGraJwA.woff) format('woff');
  unicode-range: U+0370-03FF;
}
/* latin-ext */
@font-face {
  font-family: 'Manrope';
  font-style: normal;
  font-weight: 400;
  font-display: optional;
  src: url(https://fonts.gstatic.com/s/manrope/v4/xn7_YHE41ni1AdIRqAuZuw1Bx9mbZk79FN_M-b_Tfc7AGraJwA.woff) format('woff');
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
}
/* latin */
@font-face {
  font-family: 'Manrope';
  font-style: normal;
  font-weight: 400;
  font-display: optional;
  src: url(https://fonts.gstatic.com/s/manrope/v4/xn7_YHE41ni1AdIRqAuZuw1Bx9mbZk79FN_C-b_Tfc7AGrY.woff) format('woff');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
```

I'm **self-hosting it**, and only interested in the `latin` version. And I want to use a variable font, so I changed it to: 

```css
      @font-face {
        font-family: 'Manrope';
        font-style: normal;
        font-weight: 200 800; /* Changed to use variable weight */
        font-display: optional;
        src: url(Manrope-variable-latin.woff) format('woff'); /* Changed to use self-hosted font */
        unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
      }
```

But Google Fonts is only giving me the `woff` format, I don't understand why it doesn't use woff2. Is that an issue? Shouldn't it provide woff2 (and woff as a fallback, too?)

What I want is:
- Use woff2
- Use woff as fallback (if it's still necessary)
- Use variable font with the whole `weight`: `font-weight: 200 800;`
- Use `unicode-range` to fetch only latin characters and ignore the rest

The .woff file generated by Google Fonts is only 16kB, but I'm not sure if it includes a variable font-weight, and I cannot find a woff2 version.

---

Edit: When downloading the font from https://manropefont.com/, it has a `variable/Manrop[wght].ttf` file included, but it doesn't seem web-related. And there is nothing with "variable" in the `web` folder. I'm kinda lost, maybe looking for the wrong thing?
