### ISSUE TITLE
Font looks weird on IOS

### ISSUE THREAD

**Issue by Ternowy** [sharanda/manrope#85]
Font appears differently on PC and on IPhone for cyrillic text.

PC and Android phones:
![image](https://user-images.githubusercontent.com/35680667/151027512-7bdd1d13-e9ce-4795-a7bd-8a1a7ea411c1.png)
IPhones:
![image](https://user-images.githubusercontent.com/35680667/151027682-7539eb39-9a6e-465b-9c07-a420b5736333.png)

You can observe additional spacing and lower weight.

Using with Tailwind:
```css
@font-face {
    font-family: 'Manrope';
    font-weight: 400;
    src: url(/fonts/Manrope-Regular.woff2);
}

body,html,input {
    @apply font-display;
}
```
Tailwind config:
```js
fontFamily: {
   display: ["Manrope", "sans-serif"],
},
```

**Comment by sharanda** [comment]
@Ternowy Thanks for reporting about it. But I can't tell from this description what could possibly go wrong. Is there a page I can see it myself on?

**Comment by Ternowy** [comment]
> @Ternowy Thanks for reporting about it. But I can't tell from this description what could possibly go wrong. Is there a page I can see it myself on?

Yes, you can check [vidhook.io](https://vidhook.io/)

**Comment by sharanda** [comment]
@Ternowy alright. I found 2 possible issues you might check:

The file size is inconsistent with the official version. It might have been compressed/converted with something else. I suggest you to re-download latest version from this repo or https://manropefont.com/
![image](https://user-images.githubusercontent.com/32507483/151031455-def43792-2bfe-4816-ba2a-66254bb4cd86.png)


The issue on iOS looks like the system doesn't know which font file to use. Or the font format is not correct.
```
@font-face {
    font-family: "Manrope";
    src: url(/fonts/Manrope-Regular.ttf)
}
```

You may try to change it to:
```
@font-face {
    font-family: "Manrope";
    src: url(/fonts/Manrope-Regular.ttf) format("truetype");
}
```

But I'd strongly suggest you to use WOFF2 fonts or WOFF2 variable.

**Comment by Ternowy** [comment]
> @Ternowy alright. I found 2 possible issues you might check:
> 
> The file size is inconsistent with the official version. It might have been compressed/converted with something else. I suggest you to re-download latest version from this repo or https://manropefont.com/ ![image](https://user-images.githubusercontent.com/32507483/151031455-def43792-2bfe-4816-ba2a-66254bb4cd86.png)
> 
> The issue on iOS looks like the system doesn't know which font file to use. Or the font format is not correct.
> 
> ```
> @font-face {
>     font-family: "Manrope";
>     src: url(/fonts/Manrope-Regular.ttf)
> }
> ```
> 
> You may try to change it to:
> 
> ```
> @font-face {
>     font-family: "Manrope";
>     src: url(/fonts/Manrope-Regular.ttf) format("truetype");
> }
> ```
> 
> But I'd strongly suggest you to use WOFF2 fonts or WOFF2 variable.

Thank you for answer!

I redeployed the application with your recommendations, but it still looks the same:
![image](https://user-images.githubusercontent.com/35680667/151042576-8f7f7d46-6fdd-4e32-987a-a03941be8497.png)
![image](https://user-images.githubusercontent.com/35680667/151042774-c4b37eed-f15e-4f37-a891-b823f4a986dc.png)

**Comment by Ternowy** [comment]
@sharanda I've tried other fonts and it has same problem on Iphone, I assume it's a problem of iphone/tailwind...
I would like to mark this ticket as irrelevant

**Comment by Ternowy** [comment]
@sharanda The problem was the font installation, IOS doesn't modify the font for specific weight like it android and PC do, instead it requires another font for each weight, so the solution was to include all weight variations, like on manrope website.


```css
@font-face {
    font-family: Manrope;
    src: url(/fonts/Manrope-ExtraLight.woff2) format("woff2");
    font-weight: 200
}

@font-face {
    font-family: Manrope;
    src: url(/fonts/Manrope-Light.woff2) format("woff2");
    font-weight: 300
}

@font-face {
    font-family: Manrope;
    src: url(/fonts/Manrope-Regular.woff2) format("woff2");
    font-weight: 400
}

@font-face {
    font-family: Manrope;
    src: url(/fonts/Manrope-Medium.woff2) format("woff2");
    font-weight: 500
}

@font-face {
    font-family: Manrope;
    src: url(/fonts/Manrope-SemiBold.woff2) format("woff2");
    font-weight: 600
}

@font-face {
    font-family: Manrope;
    src: url(/fonts/Manrope-Bold.woff2) format("woff2");
    font-weight: 700
}

@font-face {
    font-family: Manrope;
    src: url(/fonts/Manrope-ExtraBold.woff2) format("woff2");
    font-weight: 800
}
```
